
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveries
  template:
    metadata:
      labels:
        app: deliveries
    spec:
      containers:
        - name: deliveries
          image: mreider/taco-deliveries:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: deliveries
spec:
  selector:
    app: deliveries
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081