apiVersion: apps/v1
kind: Deployment
metadata:
  name: taco-proxy
spec:
  selector:
    matchLabels:
      app: taco-proxy
  template:
    metadata:
      labels:
        app: taco-proxy
      annotations:
        oneagent.dynatrace.com/inject: "false"
    spec:
      containers:
        - name: taco-proxy
          image: mreider/taco-proxy:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          env:
            - name: dt_token
              valueFrom:
                secretKeyRef:
                  name: tacos
                  key: dt_token
            - name: dt_endpoint
              valueFrom:
                secretKeyRef:
                  name: tacos
                  key: dt_endpoint